### ISSUE TITLE
nztrain requires javascript

### ISSUE THREAD

**Issue by ronalchn** [NZOI/nztrain#11]
Should not require javascript. Basically the right hand side is blank without javascript. Only navigation pane on left is visible. (this might be due to some jquery animation thing)

Note: other things....

Menu needs some nesting anyways. So this may be fixed as part of menu changes. Many more links can be made than would fit on the side pane. However, when it is expanded, I think it would be weird having submenus popup from there, because the side pane is too wide.

So I am thinking that the menu should be moved to the top of the page, as a thin bar across the top.

We can put some rankings/high scores of brownie points of problems solved on the left instead of the menu.

**Comment by lfairy** [comment]
Can we close this? @requalix's point remains accurate in 2019, if not more so.
