### ISSUE TITLE
Scrolling through pages on Safari is erratic due to spurious paints

### ISSUE THREAD

**Issue by tom93** [NZOI/nztrain#124]
The issue was originally reported by @Techno-coder with a proposed fix in PR #80/#83, but the fix [caused a problem](https://github.com/NZOI/nztrain/pull/83#issuecomment-590657814) and was reverted. We should try to find another fix.

**Comment by puqeko** [comment]
In Safari 14 the repainting issues seems to have gone. There is still a white bar at the top and bottom which appears as part of the scrolling snap back thingy but it does not impact the functionality of the site. I would like to suggest that we close this and related issues
