### ISSUE TITLE
Fix CI due to travis-ci.org shutting down

### ISSUE THREAD

**Issue by tom93** [NZOI/nztrain#147]
*Summary: CI is down. I suggest we switch to GitHub Actions (I'll try to finally review #82). In the meantime, can someone please disable the CI requirement (or give me admin access so I can do it myself)?*

---

Travis CI has shut down travis-ci.**org** and requires projects to migrate to travis-ci.**com** (which was originally the paid version for private repositories). I believe the free tier for open source projects (public repositories) has been replaced with a free *trial* that includes one-off credits for 1000 build minutes, and additional credits need to be manually requested from the Travis CI support team, subject to [requirements](https://travis-ci.community/t/org-com-migration-unexpectedly-comes-with-a-plan-change-for-oss-what-exactly-is-the-new-deal/10567/15). (This is despite the [migration guide](https://docs.travis-ci.com/user/migrate/open-source-repository-migration/#q-will-travis-ci-be-getting-rid-of-free-users) saying that "Travis CI will continue to offer a free tier for public or open-source repositories on travis-ci.com and will not be affected by the migration.")

We would probably meet those requirements, but it sounds like it would be an ongoing hassle. I think we'd be better off switching to another service, for example GitHub Actions. There is already a great open PR (#82) for that; I started reviewing it but never finished, I'll try to finally get that done.

In the meantime, the CI outage together with our current branch protection settings prevent merges into branch 'master'. How about we disable the CI requirement for now?

**Comment by puqeko** [comment]
Travis CI has been removed as a required status check. I agree that GitHub actions seems like the way forward. Thanks for looking at this!
