### ISSUE TITLE
Specify the Ruby version in Gemfile, .ruby-version, or similar

### ISSUE THREAD

**Issue by tom93** [NZOI/nztrain#170]
Background: Our app requires a specific Ruby version. Currently the version is hard-coded in the install scripts (scripts/install/\*) and in the obsolete .travis-ci.yml. One issue with this approach is that Dependabot is not aware of that version, so it suggests incompatible updates. Another issue is that it doesn't integrate with the GitHub Action [ruby/setup-ruby](https://github.com/ruby/setup-ruby) ([#150](https://github.com/NZOI/nztrain/pull/150)). I'd like to switch to a better method for specifying the Ruby version.

Here are the methods I am aware of and their tooling support (trickiest constraints in bold):

| Method | Supported by | Not supported by |
| --- | --- | --- |
| .ruby-version | **rbenv**, rvm, setup-ruby, [asdf](https://github.com/asdf-vm/asdf)<sup>[config required](https://github.com/asdf-vm/asdf-ruby/blob/335f356524600d76a71308963fc98b7c98ab9579/README.md#migrating-from-another-ruby-version-manager)</sup> | dependabot |
| .tool-versions | setup-ruby, asdf | rbenv, rvm, dependabot |
| Gemfile | **dependabot**, rvm (with warning<sup>1</sup>), asdf<sup>config required; [ref](https://github.com/asdf-vm/asdf-ruby/blob/335f356524600d76a71308963fc98b7c98ab9579/bin/parse-legacy-file#L7)</sup> | rbenv, setup-ruby |

Comments:
 - rbenv and RVM are used in our install scripts and it would be nice to have good integration with them for local development. Currently we don't have good integration (`cd` into the project doesn't automatically switch to the right Ruby version).
 - setup-ruby was proposed in [#150](https://github.com/NZOI/nztrain/pull/150) and seems like the best tool for running on GitHub Actions _natively_, however I think it is more likely that we will use Docker (at least to start with) because GitHub Actions doesn't let us choose the Ubuntu version.
 - asdf is a general-purpose language version manager that supports Ruby, Node.js etc. The reason I included it is that .tool-versions originates from asdf, and [#150](https://github.com/NZOI/nztrain/pull/150) proposed to use .tool-versions.

Here are the options I can think of:

**A.** Use Gemfile only.
We won't have rbenv integration, but we've managed so far without it.
We'll get RVM integration but with a warning<sup>1</sup>. I think the only way to disable this warning is to modify ~/.rvm/user/rvmrc_ignored, which I'd rather not do.
If we want to use setup-ruby in CI, we can add a step that extracts the version from the Gemfile and writes it to .ruby-version.

**B.** Use both .ruby-version and Gemfile.
This means the Ruby version will appear in two places and they'll have to be kept in sync. ~~We can add a CI check to detect inconsistencies.~~ *[Correction](https://github.com/NZOI/nztrain/issues/170#issuecomment-1433696494): Bundler automatically checks the version specifier in the Gemfile is satisfied, so no need for a custom check.*

**C.** Make .ruby-version the single source of truth, and have the Gemfile automatically look up the version using the line

```ruby
ruby "#{File.read(File.expand_path(".ruby-version", File.dirname(__FILE__)))}"
```

I think this option is too clever, and it means Dependabot won't automatically refresh its PRs when we update .ruby-version.

Thoughts?

---

<sup>1</sup> RVM produces the following warning when you `cd` into a project and the version is detected using the Gemfile:
> RVM used your Gemfile for selecting Ruby, it is all fine - Heroku does that too,
you can ignore these warnings with 'rvm rvmrc warning ignore /.../nztrain/Gemfile'.
To ignore the warning for all files run 'rvm rvmrc warning ignore allGemfiles'."

**Comment by puqeko** [comment]
I'd be in support of A. Use Gemfile only. It seems that ["the warning is there to make you aware of this feature"](https://github.com/rvm/rvm/issues/2939) and thus harmless.

**Comment by bagedevimo** [comment]
FWIW, you can't really disable the Gemfile thing and it's kinda really obvious when you have a mismatch. The last three orgs I've worked with / for use `.ruby-version`, and the people responsible also updates the Gemfiles when bumping .ruby-version, so I'm in favour of B. Bundler will automatically detect inconsistencies.

**Comment by Holmes98** [comment]
I also prefer B – I'm using rbenv and already have a locally git ignored `.ruby-version` file (I had to install a newer version of Ruby to test changes to the [NZOI site](https://github.com/NZOI/NZOI.github.io)).

**Comment by bagedevimo** [comment]
I'm using asdf and also have an ignored .ruby-version :) - GitHub Actions can also automatically install ruby via the community/ruby action but require a .ruby-version

**Comment by tom93** [comment]
> Bundler will automatically detect inconsistencies.

Oh yeah, I overlooked that. So @puqeko, based on your :+1:'s I assume we have a consensus?

**Comment by puqeko** [comment]
Yep
