### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by logan12358** [NZOI/nztrain#31]
The current selection of languages is getting outdated. It would be useful to support:

- [x] Javascript
- [x] C#
- [x] Newer Java
- [x] Newer GHC (#27)
- Probably more...

To support a new language, we need to:

- [x] Update the scripts to install the language to the `chroot` environment
- [x] Update the language database
- [ ] Update documentation (e.g. the list of NZIC languages)
- [x] Check that things work?

For now, we're blocked on deployment, but it would be good to prioritise the list of languages to add and consider any issues that may arise (e.g. input and output support/guides in Javascript).

**Comment by puqeko** [comment]
GCC #45
Java #47
Python #48
JavaScript #49

**Comment by lambda-fairy** [comment]
Since this issue has been split out into smaller ones, can we close this? @puqeko

**Comment by lambda-fairy** [comment]
I went ahead and closed this myself. Holler if you object.
