### ISSUE TITLE
Memory limits not being enforced

### ISSUE THREAD

**Issue by Holmes98** [NZOI/nztrain#51]
This is most likely due to swap being enabled – see [isolate's manual page](http://www.ucw.cz/moe/isolate.1.html#_installation). It can be fixed by disabling swap but that seems dangerous as the server is currently running on only 4 GB of physical memory.

The more viable option is to enable the swap cgroup controller. This can be done by setting `GRUB_CMDLINE_LINUX_DEFAULT="cgroup_enable=memory swapaccount=1"` in `/etc/default/grub`, then running `update-grub` and rebooting the server.

**Comment by Holmes98** [comment]
I've enabled the cgroup controller on the server and memory limits are now working again.

**Comment by tom93** [comment]
Should add a note about this to the install scripts? (Or do it automatically?)

**Comment by Holmes98** [comment]
I couldn't find any easy ways to do it automatically (the setting might have existing parameters which we probably don't want to overwrite), but if you know how to, feel free to add it. Otherwise I was thinking of just adding a note under the README.
