### ISSUE TITLE
C++11 and C++14 not judging

### ISSUE THREAD

**Issue by puqeko** [NZOI/nztrain#59]
To repeat. Submit a C++11 or C++14 solution.

The compilation step doesn't appear to be completing and the submission pends indefinitely.

Seems to have been an issue since the 20th.

![ 2020-01-22 at 12 10 43 AM](https://user-images.githubusercontent.com/12654833/72800297-e064d480-3cab-11ea-9e4f-22fb6f095f42.png)

**Comment by Holmes98** [comment]
Fixed by restarting qless – `systemctl restart qless.service`.
