### ISSUE TITLE
readline() returns undefined in V8 8.1 interpreter

### ISSUE THREAD

**Issue by lurr** [NZOI/nztrain#76]
It appears as if `readline()` is giving a result that is not of type `string` for the https://train.nzoi.org.nz/problems/24 problem, when running with the new V8 8.1 interpreter.

Reproduction code is listed below, in Python and ECMAScript.

```javascript
const nums = readline()
  .split(' ')
  .map(Number);

const min = Math.min(...nums);
const max = Math.max(...nums);

const avg = Math.floor(nums.reduce((a, b) => a + b) / 100);

console.log(min, max, avg);
```

```python
from math import floor
from functools import reduce

nums = list(map(int, input().split()))

minNum = min(nums)
maxNum = max(nums)
avgNum = floor(reduce((lambda a, b: a + b), nums) / 100)

print("{} {} {}".format(minNum, maxNum, avgNum))
```

The given problem input was used, and both cases work when tested from a command line.
```bash
$ python sample.py < input
1 100 52
$ ../d8 sample.js < input
1 100 52
```

However, when the javascript sample is uploaded `.split(' ')` fails as the result from `readline()` is `undefined`, causing a runtime error.

**Comment by Holmes98** [comment]
Thanks for catching this. This issue occurs because `readline()` returns `undefined` if the line of input does not have a trailing newline. This shouldn't happen on any newer problems since now a newline character is automatically added, but the issue may persist on older problems (pre-2015). Currently working on a fix.

**Comment by Holmes98** [comment]
Fixed by running the following code through `rails console`:

```ruby
TestCase.where("(input NOT LIKE '%\n')").find_each do |tc|
  tc.input = tc.input.dup
  tc.save
end
```
