### ISSUE TITLE
Unset encrypted_password limit in production database

### ISSUE THREAD

**Issue by tom93** [NZOI/nztrain#86]
The schema of the production database (on the server) matches the 'deployed' branch, and has a ["limit: 128" constraint](https://github.com/NZOI/nztrain/blob/801bc027569a037850452c479001376f014c0f82/db/schema.rb#L517) on the encrypted_password column of the users table. The schema in the 'master' branch (which was regenerated in commit fe025a8 by running the migrations on a clean install) does not have this constraint.

The constraint was added to the "devise" gem in commit https://github.com/heartcombo/devise/commit/27c4280eca8472415fe72134ba962c48a7fcb4e6, then later removed in commit https://github.com/heartcombo/devise/commit/ac0105d15f5bcc78f7a4b496eb52b0a5e9a27100 (with the explanation "No need to limit password"). I suggest we remove this legacy constraint from the production database (and make the schema match the 'master' branch) by running

    psql nztrain -c 'ALTER TABLE users ALTER COLUMN encrypted_password TYPE varchar(255)'

(255 is the default length)
I've tried it on a copy of the production database and it worked, but please double check my plan.

**Comment by Holmes98** [comment]
Looks good to me.

**Comment by tom93** [comment]
Done.
